name: NPC
author: Bluelands
main: Bluelands\NPC\NPCPlugin
version: 1.0.8
api: 3.0.0

commands:
  npc:
    description: NPC command.
    permission: npc.command

permissions:
  npc.command:
    default: op
    description: Allow to control command npc.
